// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etjdtuuccwhvbymzkbya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0amR0dXVjY3dodmJ5bXprYnlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNzg5NzUsImV4cCI6MjA1NzY1NDk3NX0.SnS0ksL3HWG9M058oq4-RqdrnH53917qb-21_i0varI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);